### ISSUE TITLE
Game ended but did not show end of game screen

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#488] opened 2017-10-04 18:23 UTC
Enemy kernel was destroyed and the game ended, but I was not given an option to return to the home screen

**Comment by Dbz** [comment] 2017-10-04 18:31
Playing today I am not having this issue

**Comment by AlexNisnevich** [comment] 2017-10-21 00:49
I'm going to close this for now because we can't reproduce it. If it happens again, check to see what the error is in the console.

**Closed by AlexNisnevich** 2017-10-21 00:49 UTC
Labels: basic-gameplay, bug, multiplayer

**Comment by Dbz** [comment] 2017-10-21 17:35
👍
